baseURL = "http://brettkk.github.io/"
languageCode = "zh-cn"
title = "brettkk"

theme = "mini"

paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 30  # 限制摘要字数

# pygmentsCodeFences = true                      # Enable syntax highlighting with GitHub flavoured code fences
# pygmentsStyle = "pygments"
# pygmentsUseClasses = true                      # Use CSS classes to format highlighted code
# pygmentsCodefencesGuessSyntax = true           #

# useHLJS = true


[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[params]
    archive-paginate = 30                         # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
    showReadMore = true 
    # toc = true
    showTOC = true
    mathjax = true

[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    owner = "brettkk"
    repo = "brettKK/brettkk.github.io"    # 仓库地址The repo to store comments
    issueTerm = "pathname"    #gitmentClientId = "694cecb7641cd102150b" 
	theme = "github-light"     #gitmentClientSecret = "f06f28880ee792966d06bed3d40291c77a89015c"


# Markdown 渲染器
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = false
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false

# [markup.highlight]
#     # style = 'manni' # 样式参考 https://swapoff.org/chroma/playground
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = true
#     # style = "monokai"
#     tabWidth = 4
[params.math]
    enable = true