baseURL = "http://brettkk.github.io/"
#languageCode = "zh-cn"
#title = "brettkk"

[params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = "brettKK"              # Your GitHub ID
    repo = "brettkk.github.io"               # The repo to store comments
    clientId = "8249f124b3b05e643967"           # Your client ID
    clientSecret = "xxxx"       # Your client secret