baseURL = "http://brettkk.github.io/"
languageCode = "zh-cn"
title = "brettkk"

theme = "mini"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[params]
	enableGitment = true
    gitmentClientId = "694cecb7641cd102150b" # Needed for Gitment comments
    gitmentClientSecret = "f06f28880ee792966d06bed3d40291c77a89015c" # Needed for Gitment comments