baseURL = "http://brettkk.github.io/"
languageCode = "zh-cn"
title = "brettkk"

theme = "mini"

summaryLength = 30  # 限制摘要字数


PygmentsCodeFences = true                      # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true                      # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true           #
PygmentsOptions = "linenos=table"              # 开启显示行号

showReadMore = true 

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[params]
    archive-paginate = 30                         # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
    toc = true

[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    owner = "brettkk"
    repo = "brettkk.github.io"    # 仓库地址The repo to store comments
    issueTerm = "pathname"    #gitmentClientId = "694cecb7641cd102150b" 
	theme = "github-light"     #gitmentClientSecret = "f06f28880ee792966d06bed3d40291c77a89015c"