baseURL = "http://brettkk.github.io/"
languageCode = "zh-cn"
title = "brettkk"

theme = "mini"

paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 30  # 限制摘要字数


PygmentsCodeFences = true                      # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true                      # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true           #
PygmentsOptions = "linenos=table"              # 开启显示行号


[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[params]
    archive-paginate = 30                         # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
    showReadMore = true 
    toc = true

[params.utterances]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    owner = "brettkk"
    repo = "brettkk.github.io"    # 仓库地址The repo to store comments
    issueTerm = "pathname"    #gitmentClientId = "694cecb7641cd102150b" 
	theme = "github-light"     #gitmentClientSecret = "f06f28880ee792966d06bed3d40291c77a89015c"


[params.markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[markup]
    [markup.tableOfContents]
        endLevel = 6                                  # TOC的标题结束层数（H6）
        startLevel = 2                                # TOC的标题开始层数（H1）
    [markup.goldmark.renderer]
        unsafe = false


[params.math]
    enable = true